<a href="https://colab.research.google.com/github/celsosoaresss/Machine_Learning/blob/main/Save_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importando as bibliotecas necessárias

import pandas as pd
import sklearn.model_selection as sp

In [2]:
#carregando dados

df = pd.read_csv('/content/rotatividade_clientes.csv', index_col = 0)
df.head()

,Idoso,Tempo de permanência,Valor mensal,Valor total,Sexo,Solteiro,Dependentes,Serviço telefônico,Várias linhas telefônicas,Provedor DSL,...,Streaming de filmes,Contrato de mês a mês,Contrato de um ano,Contrato de dois anos,Fatura digital,Pgto transferência bancária,Pgto cartão de crédito,Pgto cheque eletrônico,Pgto cheque enviado,Rotatividade
0,0,1,29.85,29.85,0,1,0,0,0,1,...,0,1,0,0,1,0,0,1,0,0
1,0,34,56.95,1889.50,1,0,0,1,0,1,...,0,0,1,0,0,0,0,0,1,0
2,0,2,53.85,108.15,1,0,0,1,0,1,...,0,1,0,0,1,0,0,0,1,1
3,0,45,42.30,1840.75,1,0,0,0,0,1,...,0,0,1,0,0,1,0,0,0,0
4,0,2,70.70,151.65,0,0,0,1,0,0,...,0,1,0,0,1,0,0,1,0,1

In [7]:
#separando X (independente) e y (dependente)
X = df.drop(columns = ['Rotatividade'])
y = df['Rotatividade']

X.shape, y.shape

((7032, 25), (7032,))

In [8]:
#dividindo nos conjuntos de treino e test
X_train, X_test, y_train, y_test = sp.train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5625, 25), (1407, 25), (5625,), (1407,))

In [11]:
#treinar modelo preditivo
from sklearn.linear_model import LogisticRegression

#import warnings
#warnings.filterwarnings('ignore')

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [12]:
#calcular métricas
import sklearn.metrics as mt

mt.accuracy_score(y_test, y_pred), mt.recall_score(y_test, y_pred)

(0.7874911158493249, 0.5053475935828877)

In [13]:
#salvando o modelo preditivo
import pickle as pck

pck.dump(model, open('model.dat','wb'))